name: "PR Reviewer Slack Notify Action"
description: "Blow up a channel with @s when adding people to review your PR."
branding:
  color: blue
  icon: at-sign
inputs:
  base-branch:
    description: "Branch that you will be opening PRs in to (e.g. 'staging', 'master')."
    required: true
  bot-token:
    description: "OAuth token for your Slack App Bot to sign requests to Slack's API with."
    required: true
  channel-id:
    description: "ID of the channel or conversation in Slack you would like messages posted to."
    required: true
  github-token:
    description: "Personal access token with repository rights."
    required: true
  label-name-to-watch-for:
    description: "If you would like to notify the thread of a label being applied to a PR, set this."
    required: false
    default: ""
  custom-notifier-message:
    description: "You can customize the message that will be posted as your notification"
    required: false
    default: ""
  group-to-notify:
    description: "The specific group in a channel you want to notify to, ex. @here, do not include @"
    required: false
    default: "here"
  slack-users: # id of input
    description: "This is JSON stringified array of the users you would like to be able to notify via slack when they are requested to review a PR. The format should be [{ github_username: string, slack_id: string,  slack_webhook: string }]"
    required: true
    default: "[]"
runs:
  using: "node12"
  main: "index.js"
